### ISSUE TITLE
Allow user defined sections and aliases

### ISSUE THREAD

**Issue by kbknapp** [thoughtram/clog#31]
Currently only two sections become viewable in the changelog, Features and Fixes. I'd propose allowing users to define additional sections, and the aliases of those sections in their `.clog.toml`

This issue would allow adding sections (and aliases) only, i.e. not taking away of the standard sections and aliases.

I'm thinking something like

```toml
[clog]
# ...

[sections]
MyCustom = ["mc", "mycust"]
```
